In [2]:
# imports
import requests
import os
import pandas as pd
import json

In [ ]:
'''try:
        url = "https://api.foursquare.com/v3/places/search?radius=1000&ll="+str(row['latitude'])+','+str(row['longitude'])
        headers = {"accept": "application/json"}
        headers['Authorization'] = api_key

        response = requests.get(url, headers=headers)

        print('success', response.text)
        
        # If the response was successful, no Exception will be raised
        response.raise_for_status()
    except HTTPError as http_err:
        print(f'HTTP error occurred: {http_err}')  # Python 3.6
    except Exception as err:
        print(f'Other error occurred: {err}')  # Python 3.6
    else:
        result = response.text
        break'''

# Foursquare

Send a request to Foursquare with a small radius (1000m) for all the bike stations in your city of choice.

In [40]:
# read data saved from citybikes API
df_stations = pd.read_csv('C:\\Users\\aysha\\Documents\\Python Scripts\\Statistical-Modelling-Project\\data\\bike_stations.csv', index_col=0)
df_stations.head()

api_key = os.environ["FOURSQUARE_API_KEY"]
# os.environ loads the dictionary with environment variables 
# where os.environ.keys() are all variable names

#df_stations = df_stations.reset_index()  # make sure indexes pair with number of rows

cnt=0
new_df  = pd.DataFrame() 
final_df  = pd.DataFrame() 

#sample url
#url = "https://api.foursquare.com/v3/places/search?radius=1000&ll=42.386781%2C-71.006098"
for index, row in df_stations.iterrows():
    
    url = "https://api.foursquare.com/v3/places/search?radius=1000&ll="+str(row['latitude'])+','+str(row['longitude'])
    headers = {"accept": "application/json"}
    headers['Authorization'] = api_key
    print(url)
    response = requests.get(url, headers=headers)
    data = json.loads(response.text)
    data =data['results']
    
    if cnt==0:
        new_df= pd.json_normalize(data, record_path=['categories'], meta=['fsq_id', 'name', 'distance', ['location', 'address']],meta_prefix='poi_', errors='ignore')
        new_df['free_bikes'] = row['free_bikes']
        new_df['station_lat']=row['longitude']
        new_df['station_long']=row['latitude']
        print('new_df count:',len(new_df))
        final_df = new_df
        cnt+=1
        #print(cnt)
    else:
        new_df= pd.json_normalize(data, record_path=['categories'], meta=['fsq_id', 'name', 'distance', ['location', 'address']],meta_prefix='poi_', errors='ignore')
        new_df['free_bikes'] = row['free_bikes']
        new_df['station_lat']=row['longitude']
        new_df['station_long']=row['latitude']
        final_df=pd.concat([final_df, new_df], 
                  ignore_index = True)
        print('else new_df count:',len(new_df))
        print('else final_df count:',len(final_df))
        cnt+=1
        #print(cnt)
    
    #testing data for a sample dataset
    if cnt==5:
        break
    
print("API parsing completed") 
print("Final dataset row count:")
print(final_df.shape)

#API parsing completed
#Final dataset row count:
#(15, 10)

https://api.foursquare.com/v3/places/search?radius=1000&ll=42.386781,-71.006098
new_df count: 15
https://api.foursquare.com/v3/places/search?radius=1000&ll=42.36884408289836,-71.03977829217911
else new_df count: 18
else final_df count: 33
https://api.foursquare.com/v3/places/search?radius=1000&ll=42.369536,-71.039431
else new_df count: 18
else final_df count: 51
https://api.foursquare.com/v3/places/search?radius=1000&ll=42.383532520117896,-71.01619094610214
else new_df count: 13
else final_df count: 64
https://api.foursquare.com/v3/places/search?radius=1000&ll=42.373312125824704,-71.0410200806291
else new_df count: 14
else final_df count: 78
API parsing completed
Final dataset row count:
(78, 13)

In [50]:
final_df.shape


#grouped_df=final_df.groupby(['station_lat','station_long','free_bikes']).count()

#new_df.head()

(78, 13)

Parse through the response to get the POI (such as restaurants, bars, etc) details you want (ratings, name, location, etc)

In [35]:
final_df.head()

,id,name,short_name,plural_name,icon.prefix,icon.suffix,poi_fsq_id,poi_name,poi_distance,poi_location.address,free_bikes,station_lat,station_long
0,13018,Pub,Pub,Pubs,https://ss3.4sqi.net/img/categories_v2/nightli...,.png,591f852e5d891b595cb65504,Renegade's Pub,53,1004 Bennington St,8.0,-71.006098,42.386781
1,13000,Dining and Drinking,Dining and Drinking,Dining and Drinking,https://ss3.4sqi.net/img/categories_v2/food/de...,.png,591f852e5d891b595cb65504,Renegade's Pub,53,1004 Bennington St,8.0,-71.006098,42.386781
2,13068,American Restaurant,American,American Restaurants,https://ss3.4sqi.net/img/categories_v2/food/de...,.png,4baf64acf964a52083fc3be3,Donna's Restaurant,93,980 Saratoga St,8.0,-71.006098,42.386781
3,13102,Cantonese Restaurant,Cantonese,Cantonese Restaurants,https://ss3.4sqi.net/img/categories_v2/food/as...,.png,4b415414f964a5206ec525e3,Little Asia,92,991 Bennington St,8.0,-71.006098,42.386781
4,17076,Liquor Store,Liquor Store,Liquor Stores,https://ss3.4sqi.net/img/categories_v2/shops/f...,.png,4d3b919584d46ea85b34f65c,Woody's Liquors,94,1035 Saratoga St,8.0,-71.006098,42.386781

In [39]:
final_df=pd.concat([final_df, new_df])
          
final_df.shape

(29, 13)

Put your parsed results into a DataFrame

In [51]:
#retrieved the parsed results into the DataFrame final_df in the previous step

#save the dataset into a file

final_df.to_csv('C:\\Users\\aysha\\Documents\\Python Scripts\\Statistical-Modelling-Project\\data\\FSQ_data.csv')

# Yelp

Send a request to Yelp with a small radius (1000m) for all the bike stations in your city of choice.

In [14]:
'''
#try a sample request to understand data
import requests

url = "https://api.yelp.com/v3/businesses/search?latitude=42.386781&longitude=-71.006098&radius=1000&sort_by=best_match"
api_key = os.environ["YELP_API_TOKEN"]
headers = {
    "accept": "application/json",
    "Authorization": api_key
}

response = requests.get(url, headers=headers)

print(response.text)
'''

{"error": {"code": "ACCESS_LIMIT_REACHED", "description": "You've reached the access limit for this client. See instructions for requesting a higher access limit at https://docs.developer.yelp.com/docs/fusion-rate-limiting"}}

In [13]:
'''
#work with a sample Yelp output to get the code sorted out.
f = open('C:\\Users\\aysha\\Documents\\Python Scripts\\Statistical-Modelling-Project\\data\\yelp_response.json')
 
# returns JSON object as 
# a dictionary
data = json.load(f)
 
# Iterating through the json
# list
#for i in data['emp_details']:
#    print(i)
 
# Closing file
f.close()

data = data['businesses']

#new_df=pd.DataFrame()

#new_df=pd.json_normalize(data)

new_df =pd.json_normalize(data, record_path=['categories'], meta=['id', 'name', 'distance', ['location', 'address1'], 'rating'],meta_prefix='poi_', errors='ignore')

new_df['free_bikes'] = 3
new_df['station_lat']=1.12
new_df['station_long']=3.44

new_df
'''

,alias,title,poi_id,poi_name,poi_distance,poi_location.address1,poi_rating,free_bikes,station_lat,station_long
0,mexican,Mexican,gjWtb3F23YxfYvRHWbvWWA,Angela's Cafe - Orient Heights,40.670336,1012 Bennington St,4.5,3,1.12,3.44
1,breakfast_brunch,Breakfast & Brunch,gjWtb3F23YxfYvRHWbvWWA,Angela's Cafe - Orient Heights,40.670336,1012 Bennington St,4.5,3,1.12,3.44
2,chinese,Chinese,nwU1tKh-D68B7Z44DbDwXg,Little Asia Restaurant,94.503416,991 Bennington St,4.0,3,1.12,3.44
3,italian,Italian,Zm29bLI2eYCevnse4n2U1g,Luna's Restaurant Italian and Latin Cuisine,251.881247,945 Saratoga St,4.5,3,1.12,3.44
4,latin,Latin American,Zm29bLI2eYCevnse4n2U1g,Luna's Restaurant Italian and Latin Cuisine,251.881247,945 Saratoga St,4.5,3,1.12,3.44
5,bars,Bars,Zm29bLI2eYCevnse4n2U1g,Luna's Restaurant Italian and Latin Cuisine,251.881247,945 Saratoga St,4.5,3,1.12,3.44
6,pubs,Pubs,CJ0DuAPIract7wPMWgsXbg,Renegade's Pub,56.202395,1004 Bennington St,4.0,3,1.12,3.44
7,burgers,Burgers,CJ0DuAPIract7wPMWgsXbg,Renegade's Pub,56.202395,1004 Bennington St,4.0,3,1.12,3.44
8,mexican,Mexican,tVhXK2l9iMwTqkeWDWDiTQ,Mi Pueblito Orient Heights,207.015295,964 Saratoga St,3.5,3,1.12,3.44
9,seafood,Seafood,tVhXK2l9iMwTqkeWDWDiTQ,Mi Pueblito Orient Heights,207.015295,964 Saratoga St,3.5,3,1.12,3.44
10,breakfast_brunch,Breakfast & Brunch,tVhXK2l9iMwTqkeWDWDiTQ,Mi Pueblito Orient Heights,207.015295,964 Saratoga St,3.5,3,1.12,3.44
11,vietnamese,Vietnamese,7GuI717B8NCEiKB5VVpOZg,New Saigon,112.067427,985 Bennington St,4.5,3,1.12,3.44
12,sushi,Sushi Bars,C3-m3wOZfYp7tNqKyHUcGQ,Sunny Cafe,62.308751,1000 Bennington St,4.5,3,1.12,3.44
13,delis,Delis,RigU2n4W4NCl3bdPgRdd6A,Milano's Delicatessen,110.48043,978 Saratoga St,4.0,3,1.12,3.44
14,pizza,Pizza,RigU2n4W4NCl3bdPgRdd6A,Milano's Delicatessen,110.48043,978 Saratoga St,4.0,3,1.12,3.44
15,coffee,Coffee & Tea,RigU2n4W4NCl3bdPgRdd6A,Milano's Delicatessen,110.48043,978 Saratoga St,4.0,3,1.12,3.44
16,italian,Italian,vSFwSQtaWAcGA166_HOQAg,Sammy Carlo's Delicatessen & Catering,1098.389169,567 Bennington St,4.5,3,1.12,3.44
17,tradamerican,American,vSFwSQtaWAcGA166_HOQAg,Sammy Carlo's Delicatessen & Catering,1098.389169,567 Bennington St,4.5,3,1.12,3.44
18,delis,Delis,vSFwSQtaWAcGA166_HOQAg,Sammy Carlo's Delicatessen & Catering,1098.389169,567 Bennington St,4.5,3,1.12,3.44
19,seafood,Seafood,8RMMUl3Z6AZtyfh6exjCqQ,Royal Roast Beef & Seafood,412.398241,752 Bennington St,4.0,3,1.12,3.44
20,tradamerican,American,8RMMUl3Z6AZtyfh6exjCqQ,Royal Roast Beef & Seafood,412.398241,752 Bennington St,4.0,3,1.12,3.44
21,latin,Latin American,XtwKkI3vEcJczmGY14Y92A,El Kiosco Restaurant,133.089599,972 Saratoga St,4.0,3,1.12,3.44
22,bars,Bars,XtwKkI3vEcJczmGY14Y92A,El Kiosco Restaurant,133.089599,972 Saratoga St,4.0,3,1.12,3.44
23,colombian,Colombian,QjOnSACHuMXbMkvmwLvjFA,Melodias,130.352532,1045 Saratoga St,4.0,3,1.12,3.44
24,pizza,Pizza,J8q0tmKrohIw6We0shrLig,Woody's Pizza & Liquors,106.695605,9 Barnes Ave,2.5,3,1.12,3.44
25,desserts,Desserts,gajOQX7gzaJFyKENyUDvog,Saratoga Market Ice Cream,402.943922,16 Trident St,4.5,3,1.12,3.44
26,icecream,Ice Cream & Frozen Yogurt,gajOQX7gzaJFyKENyUDvog,Saratoga Market Ice Cream,402.943922,16 Trident St,4.5,3,1.12,3.44
27,bars,Bars,YR3OMSl_ZzL9ucZRo0szXw,La Fonda Colombiana,133.120791,972 Saratoga St,4.0,3,1.12,3.44
28,colombian,Colombian,YR3OMSl_ZzL9ucZRo0szXw,La Fonda Colombiana,133.120791,972 Saratoga St,4.0,3,1.12,3.44
29,donuts,Donuts,JalbAkIj9PTf7_1UnXx2Vg,Dunkin',208.470597,951 Bennington St E,2.0,3,1.12,3.44
30,coffee,Coffee & Tea,JalbAkIj9PTf7_1UnXx2Vg,Dunkin',208.470597,951 Bennington St E,2.0,3,1.12,3.44
31,colombian,Colombian,aAntWIjPrU3Pf4Pr_m7dBg,Napoles Restaurant,840.095612,1233 Bennington St,3.0,3,1.12,3.44
32,bars,Bars,aAntWIjPrU3Pf4Pr_m7dBg,Napoles Restaurant,840.095612,1233 Bennington St,3.0,3,1.12,3.44
33,buffets,Buffets,aAntWIjPrU3Pf4Pr_m7dBg,Napoles Restaurant,840.095612,1233 Bennington St,3.0,3,1.12,3.44
34,pizza,Pizza,Wk_eGwRMqbqdV9b3HzVP9w,Woodys Pizza EF,106.546205,9 Barnes Ave,1.0,3,1.12,3.44
35,burgers,Burgers,Wk_eGwRMqbqdV9b3HzVP9w,Woodys Pizza EF,106.546205,9 Barnes Ave,1.0,3,1.12,3.44
36,wraps,Wraps,Wk_eGwRMqbqdV9b3HzVP9w,Woodys Pizza EF,106.546205,9 Barnes Ave,1.0,3,1.12,3.44
37,coffee,Coffee & Tea,QKNLbA_v2PmlAr2yoyP0Xg,STARBUCKS COFFEE,828.77316,430 William F McClellan Hwy,3.0,3,1.12,3.44
38,parks,Parks,FekacfLT0iJv6fn6T1xTOg,Constitution Beach,596.091099,799 Bennington St,4.0,3,1.12,3.44
39,swimmingpools,Swimming Pools,FekacfLT0iJv6fn6T1xTOg,Constitution Beach,596.091099,799 Bennington St,4.0,3,1.12,3.44
40,beaches,Beaches,FekacfLT0iJv6fn6T1xTOg,Constitution Beach,596.091099,799 Bennington St,4.0,3,1.12,3.44

In [53]:
#ACTUAL CODE
# read data saved from citybikes API
df_stations = pd.read_csv('C:\\Users\\aysha\\Documents\\Python Scripts\\Statistical-Modelling-Project\\data\\bike_stations.csv', index_col=0)
df_stations.head()

api_key = os.environ["YELP_API_TOKEN"]
# os.environ loads the dictionary with environment variables 
# where os.environ.keys() are all variable names


cnt=0
new_df  = pd.DataFrame() 
final_df  = pd.DataFrame() 

#sample url
#url = "https://api.yelp.com/v3/businesses/search?latitude=42.386781&longitude=-71.006098&radius=1000&sort_by=best_match"
for index, row in df_stations.iterrows():
    
    url = "https://api.yelp.com/v3/businesses/search?radius=1000&sort_by=best_match&latitude="+str(row['latitude'])+'&longitude='+str(row['longitude'])
    headers = {"accept": "application/json"}
    headers['Authorization'] = api_key
    print(url)
    
    #call API
    response = requests.get(url, headers=headers)
    data = json.loads(response.text)
    data =data['businesses']
    
    if cnt==0:
        new_df=final_df = pd.json_normalize(data, record_path=['categories'], meta=['id', 'name', 'distance', ['location', 'address1'], 'rating'],meta_prefix='poi_', errors='ignore')
        new_df['free_bikes'] = row['free_bikes']
        new_df['station_lat']=row['longitude']
        new_df['station_long']=row['latitude']
        final_df=new_df
        print('new_df count:',len(new_df))
        cnt+=1
        #print(cnt)
    else:
        new_df= pd.json_normalize(data, record_path=['categories'], meta=['id', 'name', 'distance', ['location', 'address1'], 'rating'],meta_prefix='poi_', errors='ignore')
        new_df['free_bikes'] = row['free_bikes']
        new_df['station_lat']=row['longitude']
        new_df['station_long']=row['latitude']
        final_df=pd.concat([final_df, new_df], ignore_index = True)
        print('else new_df count:',len(new_df))
        print('else final_df count:',len(final_df))
        cnt+=1
        #print(cnt)
    
    #testing data for a sample dataset
    if cnt==5:
        break
    
print("API parsing completed") 
print("Final dataset row count:")
print(final_df.shape)

#API parsing completed
#Final dataset row count:
#(41, 7)

https://api.yelp.com/v3/businesses/search?radius=1000&sort_by=best_match&latitude=42.386781&longitude=-71.006098
new_df count: 41
https://api.yelp.com/v3/businesses/search?radius=1000&sort_by=best_match&latitude=42.36884408289836&longitude=-71.03977829217911
else new_df count: 42
else final_df count: 83
https://api.yelp.com/v3/businesses/search?radius=1000&sort_by=best_match&latitude=42.369536&longitude=-71.039431
else new_df count: 41
else final_df count: 124
https://api.yelp.com/v3/businesses/search?radius=1000&sort_by=best_match&latitude=42.383532520117896&longitude=-71.01619094610214
else new_df count: 43
else final_df count: 167
https://api.yelp.com/v3/businesses/search?radius=1000&sort_by=best_match&latitude=42.373312125824704&longitude=-71.0410200806291
else new_df count: 45
else final_df count: 212
API parsing completed
Final dataset row count:
(212, 10)

Parse through the response to get the POI (such as restaurants, bars, etc) details you want (ratings, name, location, etc)

In [15]:
#retrieved the parsed results into the DataFrame "final_df" in the previous step as part of invoking API and parsing results

final_df.head()

Empty DataFrame
Columns: []
Index: []

Put your parsed results into a DataFrame

In [7]:
#save the dataset into a file

final_df.to_csv('C:\\Users\\aysha\\Documents\\Python Scripts\\Statistical-Modelling-Project\\data\\Yelp_data.csv')

# Comparing Results

Which API provided you with more complete data? Provide an explanation.

*In my opinion, Yelp provided a more complete dataset with valuable information such as rating, review count, phone number information etc. These are valuable information to bring wholeness to the data related to the point of interest.*

Get the top 10 restaurants according to their rating

In [48]:
#get the restaurants and their rating
df_poi = pd.read_csv('C:\\Users\\aysha\\Documents\\Python Scripts\\Statistical-Modelling-Project\\data\\Yelp_data.csv', index_col=0)
df_poi.head(40)

#get restaurants
mask = df_poi['poi_name'].str.contains('Restaurant', case=False, na=False)

restaurants = df_poi[mask]

restaurants = restaurants[['poi_name','poi_rating']]

restaurants_df = pd.DataFrame(restaurants) 

#remove duplicates
restaurants_df.drop_duplicates(inplace=True)

#restaurants_df = restaurants_df.reset_index()

restaurants_df.sort_values('poi_rating',inplace=True, ascending=False)

restaurants_df.head(10)

                                       poi_name  poi_rating
2   Luna's Restaurant Italian and Latin Cuisine         4.5
5                        Little Asia Restaurant         4.0
19                         El Kiosco Restaurant         4.0

In [11]:
df_poi.value_counts('title')

title
Bars                         3
Coffee & Tea                 3
American                     2
Seafood                      2
Mexican                      2
Latin American               2
Italian                      2
Fast Food                    2
Delis                        2
Pizza                        2
Colombian                    2
Burgers                      2
Breakfast & Brunch           2
Sandwiches                   1
Sushi Bars                   1
Swimming Pools               1
Pubs                         1
Ice Cream & Frozen Yogurt    1
Parks                        1
Donuts                       1
Desserts                     1
Chinese                      1
Beaches                      1
Vietnamese                   1
Name: count, dtype: int64